### ISSUE TITLE
won't build with mariadb-10.1

### ISSUE THREAD

**Issue by jochenklar** [aipescience/mysql_sphere#7]
`mariadb-server 10.1.23-9+deb9u1` doesn't provide `mysqlbug` anymore.

**Comment by jochenklar** [comment]
in addition `mariadb-server 10.1.23`'s base64.h is not compatible.

```
/home/jochen/code/mysql_sphere/src/serialiser.cc:213:56: error: macro "base64_decode" requires 5 arguments, but only 4 given
   if(base64_decode(input, inputLen, decodedString, NULL) <= 0) {
                                                        ^
/home/jochen/code/mysql_sphere/src/serialiser.cc: In function ‘MYSQL_SPHERE_TYPES decode(char*, size_t, void**)’:
/home/jochen/code/mysql_sphere/src/serialiser.cc:213:6: error: ‘base64_decode’ was not declared in this scope
   if(base64_decode(input, inputLen, decodedString, NULL) <= 0) {
      ^~~~~~~~~~~~~
```
